version: "3.9"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.production
        ports:
            - '8080:8080'
        command: nodos server -h 0.0.0.0
